"""KD hyperparameter sensitivity ablation on a single cross-validation fold.

This is a single-split sensitivity analysis that complements the cross-validated
main study. Because the temperature $T$ and weight $\\alpha$ affect only the
student's distillation loss and not the teacher, the teacher is trained
**once** on the chosen fold's training split and then reused (frozen) for every
$(\\alpha, T)$ setting. Each student is evaluated on the same fold's test split.

By default the fold is fold 0 of the same stratified partition used by the main
study (``src.cross_validate``), so the ablation is aligned with that protocol.
Two one-dimensional sweeps are run, crossing at the default configuration:

  - temperature sweep at fixed ``alpha_center``;
  - alpha sweep at fixed ``temperature_center``.

The shared center point is trained only once. Results are point estimates
without fold error bars, so small differences should be read as "flat / robust"
rather than as a ranking.

Usage:
    python -m src.ablate_kd --config configs/ablation_resnet50_cassava.yaml
"""

from __future__ import annotations

import argparse
import csv
from typing import Any

import torch

from src.cross_validate import (
    _configure_cuda_backend,
    _train_distillation,
    _train_supervised,
)
from src.data import get_cv_dataloaders
from src.evaluate import evaluate_model
from src.models import build_model
from src.utils import (
    count_parameters,
    ensure_dir,
    get_device,
    load_yaml_config,
    save_json,
    set_seed,
)


def _distill_cell(
    cfg: dict[str, Any],
    teacher: torch.nn.Module,
    loaders: tuple,
    class_names: list[str],
    device: torch.device,
    alpha: float,
    temperature: float,
    scaler: "torch.cuda.amp.GradScaler | None",
) -> dict[str, Any]:
    """Distill a fresh student from the frozen teacher for one (alpha, T) cell."""
    train_loader, val_loader, test_loader = loaders
    # Re-seed so every cell starts from the same student initialization.
    set_seed(cfg.get("seed", 42))
    student = build_model(
        cfg.get("student_model_name", "mobilenet_v3_small"),
        num_classes=len(class_names),
        pretrained=cfg.get("pretrained", True),
    ).to(device)
    student = _train_distillation(
        student, teacher, train_loader, val_loader, device,
        epochs=cfg.get("epochs", 15),
        lr=cfg.get("learning_rate", 0.0005),
        weight_decay=cfg.get("weight_decay", 0.0001),
        alpha=alpha,
        temperature=temperature,
        scaler=scaler,
    )
    res = evaluate_model(student, test_loader, device, class_names)
    return {
        "accuracy": res["accuracy"],
        "macro_precision": res["macro_precision"],
        "macro_recall": res["macro_recall"],
        "macro_f1": res["macro_f1"],
        "parameters": count_parameters(student),
    }


def _write_csv(records: list[dict[str, Any]], path) -> None:
    fields = ["sweep", "alpha", "temperature", "accuracy", "macro_precision",
              "macro_recall", "macro_f1"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(records)


def _write_latex(records: list[dict[str, Any]], path, cfg: dict[str, Any],
                 t_center: float, a_center: float) -> None:
    teacher = str(cfg.get("teacher_model_name", "resnet50")).replace("_", r"\_")

    def row(r: dict[str, Any]) -> str:
        is_center = abs(r["alpha"] - a_center) < 1e-9 and abs(r["temperature"] - t_center) < 1e-9
        mark = r"$^{\dagger}$" if is_center else ""
        return (
            f"    {r['sweep']} & {r['temperature']:g} & {r['alpha']:g}{mark} & "
            f"{r['accuracy']*100:.2f} & {r['macro_precision']*100:.2f} & "
            f"{r['macro_recall']*100:.2f} & {r['macro_f1']*100:.2f} \\\\"
        )

    body = "\n".join(row(r) for r in records)
    tex = (
        "% Auto-generated by src.ablate_kd -- do not edit by hand.\n"
        "\\begin{table}\n"
        "  \\centering\n"
        f"  \\caption{{Single-split KD sensitivity analysis for the "
        f"{teacher} teacher (fold 0 of the Cassava cross-validation split). "
        "Temperature is swept at $\\alpha=" f"{a_center:g}" "$ and $\\alpha$ at "
        "$T=" f"{t_center:g}" "$; $^{\\dagger}$ marks the default used in the "
        "main study. Precision, recall, and F1 are macro-averaged. "
        "Values are single-split point estimates (no fold error bars).}\n"
        "  \\label{tab:ablation}\n"
        "  \\begin{tabular}{llrrrrr}\n"
        "    \\toprule\n"
        "    Sweep & $T$ & $\\alpha$ & Accuracy (\\%) & Precision (\\%) & Recall (\\%) & Macro-F1 (\\%) \\\\\n"
        "    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    path.write_text(tex, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="KD temperature/alpha sensitivity ablation.")
    parser.add_argument("--config", required=True, help="Path to ablation YAML config.")
    args = parser.parse_args()

    cfg = load_yaml_config(args.config)
    seed = cfg.get("seed", 42)
    set_seed(seed)
    device = get_device()
    _configure_cuda_backend()
    output_dir = ensure_dir(cfg.get("output_dir", "outputs/ablation"))

    fold = int(cfg.get("fold", 0))
    n_folds = int(cfg.get("n_folds", 5))

    print(f"\n{'='*64}")
    print("KD SENSITIVITY ABLATION (single split)")
    print(f"Experiment : {cfg.get('experiment_name', 'unnamed')}")
    print(f"Teacher    : {cfg.get('teacher_model_name')}  (trained once on fold {fold})")
    print(f"Student    : {cfg.get('student_model_name')}")
    print(f"Device     : {device}")
    print(f"{'='*64}")

    train_loader, val_loader, test_loader, class_names = get_cv_dataloaders(
        data_dir=cfg["data_dir"],
        n_folds=n_folds,
        fold=fold,
        image_size=cfg.get("image_size", 224),
        batch_size=cfg.get("batch_size", 64),
        val_ratio=cfg.get("val_ratio", 0.15),
        seed=seed,
        num_workers=cfg.get("num_workers", 2),
        subset_prefix=cfg.get("subset_prefix") or None,
    )
    loaders = (train_loader, val_loader, test_loader)

    scaler = torch.cuda.amp.GradScaler() if device.type == "cuda" else None

    # ---- teacher trained once, then frozen and reused for every cell ----
    print(f"\nTraining teacher once (fold {fold}, "
          f"{len(train_loader.dataset)} train images)...")
    set_seed(seed)
    teacher = build_model(
        cfg["teacher_model_name"],
        num_classes=len(class_names),
        pretrained=cfg.get("pretrained", True),
    ).to(device)
    teacher = _train_supervised(
        teacher, train_loader, val_loader, device,
        epochs=cfg.get("teacher_epochs", 10),
        lr=cfg.get("teacher_learning_rate", 0.0003),
        weight_decay=cfg.get("weight_decay", 0.0001),
        scaler=scaler,
        desc=f"teacher:{cfg['teacher_model_name']}",
    )
    for p in teacher.parameters():
        p.requires_grad_(False)

    # ---- sweeps ----
    t_center = float(cfg.get("temperature_center", 4.0))
    a_center = float(cfg.get("alpha_center", 0.7))
    t_values = [float(x) for x in cfg.get("temperature_sweep", [1.0, 2.0, 4.0, 8.0])]
    a_values = [float(x) for x in cfg.get("alpha_sweep", [0.3, 0.5, 0.7, 0.9])]

    cache: dict[tuple, dict[str, Any]] = {}
    records: list[dict[str, Any]] = []

    def run(alpha: float, temperature: float, sweep: str) -> None:
        key = (round(alpha, 6), round(temperature, 6))
        if key not in cache:
            print(f"\n  distill  alpha={alpha:g}  T={temperature:g}")
            cache[key] = _distill_cell(
                cfg, teacher, loaders, class_names, device, alpha, temperature, scaler
            )
            m = cache[key]
            print(f"    acc={m['accuracy']:.4f}  macro_f1={m['macro_f1']:.4f}")
        m = cache[key]
        records.append({"sweep": sweep, "alpha": alpha, "temperature": temperature, **m})

    print(f"\nTemperature sweep at alpha={a_center:g}: {t_values}")
    for T in t_values:
        run(a_center, T, "temperature")

    print(f"\nAlpha sweep at T={t_center:g}: {a_values}")
    for a in a_values:
        run(a, t_center, "alpha")

    # ---- report ----
    print(f"\n{'='*64}")
    print("ABLATION SUMMARY (single split, fold "
          f"{fold})")
    print(f"  {'sweep':12s} {'T':>5s} {'alpha':>6s}  {'acc':>7s}  {'macroF1':>7s}")
    for r in records:
        print(f"  {r['sweep']:12s} {r['temperature']:>5g} {r['alpha']:>6g}  "
              f"{r['accuracy']*100:>6.2f}%  {r['macro_f1']*100:>6.2f}%")
    print(f"{'='*64}\n")

    # ---- persist ----
    payload = {
        "experiment_name": cfg.get("experiment_name"),
        "teacher_model_name": cfg.get("teacher_model_name"),
        "student_model_name": cfg.get("student_model_name"),
        "data_dir": str(cfg.get("data_dir", "")),
        "fold": fold,
        "n_folds": n_folds,
        "temperature_center": t_center,
        "alpha_center": a_center,
        "records": records,
    }
    save_json(payload, output_dir / "ablation_results.json")
    _write_csv(records, output_dir / "ablation.csv")
    _write_latex(records, output_dir / "ablation_summary.tex", cfg, t_center, a_center)

    print(f"Saved: {output_dir / 'ablation_results.json'}")
    print(f"Saved: {output_dir / 'ablation.csv'}")
    print(f"Saved: {output_dir / 'ablation_summary.tex'}")


if __name__ == "__main__":
    main()
